language: node_js

cache:
  # Yarn 2 does not store dependencies in node_modules anymore, at least not by default.
  # If you are using the node-modules plugin, remove the `npm: false` line.
  # npm: false
  # Yarn 2 caches to the local .yarn directory, not the Travis default `$HOME/.yarn` 
  directories:
    - ./.yarn/cache

before_install:
  # Upgrade Yarn 1.x: https://classic.yarnpkg.com/en/docs/install
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Then the local Yarn 2 should be available and get used
  - yarn -v

# Use custom install step as Travis by default uses the --frozen-lockfile flag, which is deprecated
install: yarn

node_js:
  - '12'
script:
  - yarn test
  - yarn build
install:
  - yarn install
branches:
  only:
    - main